config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  
  resources :users
  resources :versions do
    member do
      get :fire_job_one
    end
    collection do
      get 'fire_job_2/:id' => :fire_job_2, as: 'versions_fire_job_2'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/searchable.rb
require "elasticsearch/model"

module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    after_commit :index_document, if: :persisted?
    after_commit :delete_document, on: [:destroy]
  end

  private

  def index_document
    __elasticsearch__.index_document
  end

  def delete_document 
    __elasticsearch__.delete_document
  end
end

app/models/user.rb
class User < ApplicationRecord
    after_commit :clear_cache

    def clear_cache
        $redis.del("users")
    end
end

app/models/version.rb
class Version < ApplicationRecord
    # include Searchable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = $redis.get("users")
    if(@users.nil?)
      @users = User.all.to_json
      $redis.set("users", @users)
    end
    @users = JSON.load(@users)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        UserMailer.with(user: @user).welcome_email.deliver
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :set_version, only: [:show, :edit, :update, :destroy]

  # GET /versions
  # GET /versions.json
  def index
    @versions = Version.limit(50)
  end

  # GET /versions/1
  # GET /versions/1.json
  def show
  end

  # GET /versions/new
  def new
    @version = Version.new
  end

  # GET /versions/1/edit
  def edit
  end

  # POST /versions
  # POST /versions.json
  def create
    @version = Version.new(version_params)

    respond_to do |format|
      if @version.save
        format.html { redirect_to @version, notice: 'Version was successfully created.' }
        format.json { render :show, status: :created, location: @version }
      else
        format.html { render :new }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /versions/1
  # PATCH/PUT /versions/1.json
  def update
    respond_to do |format|
      if @version.update(version_params)
        format.html { redirect_to @version, notice: 'Version was successfully updated.' }
        format.json { render :show, status: :ok, location: @version }
      else
        format.html { render :edit }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /versions/1
  # DELETE /versions/1.json
  def destroy
    @version.destroy
    respond_to do |format|
      format.html { redirect_to versions_url, notice: 'Version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fire_job_one
    JobOneJob.set(wait: 2.minutes).perform_later(params[:id])
    redirect_to versions_path, notice: "Job_1(#{params[:id]}) fired successfully destroyed."
  end

  def fire_job_2
    # JobTwoJob.set(wait: 1.minutes).perform_later(params[:id])
    TestFirstWorker.perform_in(1.minutes, params[:id])
    redirect_to versions_path, notice: "Job_2(#{params[:id]}) fired successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_version
      @version = Version.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def version_params
      params.require(:version).permit(:item_type, :whodunnit_type, :object)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElasticsearchDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table border="1px">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user["name"] %></td>
        <td><%= user["email"] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/versions/_form.html.erb
<%= form_with(model: version, local: true) do |form| %>
  <% if version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
        <% version.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_type %>
    <%= form.text_field :item_type %>
  </div>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.text_field :item_id %>
  </div>

  <div class="field">
    <%= form.label :integer %>
    <%= form.text_field :integer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/versions/edit.html.erb
<h1>Editing Version</h1>

<%= render 'form', version: @version %>

<%= link_to 'Show', @version %> |
<%= link_to 'Back', versions_path %>

app/views/versions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Versions</h1>

<table border="2px">
  <thead>
    <tr>
      <th>Item type</th>
      <th>whodunnit_type</th>
      <%
=begin%>
 <th>object</th> 
<%
=end%>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @versions.each do |version| %>
      <tr>
        <td><%= version.item_type %></td>
        <td><%= version.whodunnit_type %></td>
        <%
=begin%>
 <td><%= version.object %></td> 
<%
=end%>
        <td><%= link_to 'Show', version %></td>
        <td><%= link_to 'Edit', edit_version_path(version) %></td>
        <td><%= link_to 'Destroy', version, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Fire Job 1', fire_job_one_version_path(version) %></td>
        <td><%= link_to 'Fire Job 2', versions_fire_job_2_versions_path(version) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Version', new_version_path %>

app/views/versions/new.html.erb
<h1>New Version</h1>

<%= render 'form', version: @version %>

<%= link_to 'Back', versions_path %>

app/views/versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item type:</strong>
  <%= @version.item_type %>
</p>

<p>
  <strong>Item:</strong>
  <%= @version.item_id %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @version.integer %>
</p>

<%= link_to 'Edit', edit_version_path(@version) %> |
<%= link_to 'Back', versions_path %>